name: guardian-bedrock-e2e

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the e2e against'
        required: true
        default: ':stage'
        type: choice
        options:
          - :stage
          - :prod
          - :dev

jobs:
  guardiane2e:
    name: 'Guardian e2e Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          npm ci
          npm i -D allure-playwright
          npm i -D allure-commandline

      - name: Install Playwright Browsers
        run: |
          npm install -D @playwright/test --with-deps
          npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html,line,allure-playwright --retries=2
        env:
          TESTACCOUNT_EMAIL: ${{ secrets.TESTACCOUNT_EMAIL }}
          TESTACCOUNT_PASSWORD: ${{ secrets.TESTACCOUNT_PASSWORD }}
          TEST_BASE_URL: ${{ secrets.TEST_BASE_URL }}
          TEST_EXPECT_URL: ${{ secrets.TEST_EXPECT_URL }}

      - name: Build Allure report
        run: npm run report:build

      - uses: actions/upload-artifact@master
        with:
          name: pw-report
          path: playwright-report/
          retention-days: 20

      - uses: actions/upload-artifact@master
        with:
          name: github-pages
          path: allure-report/
          retention-days: 30

      - name: Generate Artifact for ${{ inputs.environment != null && inputs.environment || ':stage' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: allure-report/

  publish:
    needs: guardiane2e

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest
    steps:
      - name: Publish to github pages
        uses: actions/deploy-pages@v1
        with:          
          artifact_name: github-pages