name: guardian-bedrock-e2e

on:
  schedule:
    - cron: '0 */3 * * *'

  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment to run the e2e against'
          required: true
          default: 'stage'
          type: choice
          options:
          - stage
          - prod
          - dev
jobs:
  guardiane2e:
    name: 'Guardian e2e Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest    
    steps:
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: |
          npm install -D @playwright/test --with-deps
          npx playwright install

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          TESTACCOUNT_EMAIL: ${{ secrets.TESTACCOUNT_EMAIL }}
          TESTACCOUNT_PASSWORD: ${{ secrets.TESTACCOUNT_PASSWORD }}
          TEST_BASE_URL: ${{ secrets.TEST_BASE_URL }}
          TEST_EXPECT_URL: ${{ secrets.TEST_EXPECT_URL }}

      - uses: actions/upload-artifact@master
        with:
          name: github-pages
          path: playwright-report/
          retention-days: 20

      - name: Generate Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: playwright-report/

      - name: Check env variables
        run: echo =========== chosen env variable ${{ inputs.environment }}        

  publish:
    needs: guardiane2e

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest
    steps:
      - name: Publish to github pages
        uses: actions/deploy-pages@v1
        with:          
          artifact_name: github-pages